function run_view(view_path, mip_num, mean, std, n_split, ...
    n_slice_per_stack, theta, factor, volume_num, gpu_index, ...
    n_pixel ,n_over_lab,layer1_shift_h ,layer1_shift_w ...
    ,layer3_shift_h ,layer3_shift_w, using_doef_data,z_num_per_stack, ...
    scan_in_lens,dl_path)
    
    temp = dir(fullfile(view_path,'H_*'));
    H_name = {temp.name};

    H_count = 0;  
    for i = 1:1
    data_type = 0;
 
    data_path = fullfile(view_path, H_name{i});
    data_count = H_count;

    fprintf([strrep(view_path,'\','/'),'\n']);   
    count = run_all(data_path, view_path, mip_num, mean, std, ...   
         n_split, n_slice_per_stack, theta, factor, ...
        data_type, data_count, volume_num, gpu_index, ...
        n_pixel ,n_over_lab,layer1_shift_h ,layer1_shift_w ...
        ,layer3_shift_h ,layer3_shift_w, using_doef_data,z_num_per_stack, ...
        H_name,scan_in_lens,dl_path);   
    H_count = H_count + count;
    end
end

