#### general settings
use_tb_logger: true
model: SingleModel
distortion: sr
scale: 1
gpu_ids: [ 0 ]
cpu_threads_num: 5

network_C:
  which_model_C: Unet
  uptype: upsample
  out_nc: 1
  n_fea: 64
  num_g: 5
  num_b: 10

network_D_HR:
  which_model_D_HR: Unet_discriminator_sn
  in_nc: 1
  nf: 64

#### path

path:
#  pretrain_model_C: ~
#  pretrain_model_D: ~
  strict_load: true


train:
  batch_size: 2
  lr_C: !!float 1e-4
  beta1: 0.9
  beta2: 0.99
  niter: !!float 50000
  warmup_iter: -1  # no warm up
  #
  lr_scheme: CosineAnnealingLR_Restart
  T_period: [50000]
  eta_min: !!float 1e-7
  #
#  lr_scheme: MultiStepLR
#  lr_steps: [ 30000, 50000, 80000, 110000, 130000, 140000 ]
#  lr_gamma: 0.5


  pixel_criterion_back: l1
  feature_criterion: l1

  weight_decay_C: 0
  gradient_clipping: 10

  manual_seed: 10

  lambda_rec_back: 1
  lambda_gan: !!float 0.1
  lambda_feature: 0.01


  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    range_norm: false
    criterion: l1

  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  gan_type: gan
  D_update_ratio: 1

  D_init_iters: !!float 1000

  val_freq: !!float 1000
#### logger

logger:
  print_freq: 1
  save_checkpoint_freq: !!float 1000
